#! /bin/sh
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███?
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

pgrep -x sxhkd >/dev/null || sxhkd &

xrandr --output HDMI-1 --same-as eDP-1

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Zathura state=tiled

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
nitrogen --restore &
polybar mybar &

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen /Pictures/wall/lain.png
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
