#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ############################################################################## 
mpd $HOME/.config/mpd/mpd.conf
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

feh --bg-fill "$HOME/Pictures/Wallpapers/itb.png"
xrandr --rate 144 &
sh $HOME/.config/polybar/launch.sh

xset r rate 250 40
xsetroot -cursor_name left_ptr &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bpsc rule -a Vivaldi-stable desktop=^1
bspc rule -a vivaldi-stable desktop=^1
bspc rule -a discord desktop=^4
bspc rule -a spotify desktop=^3
bspc rule -a vscode desktop=^2
bspc rule -a code desktop=^2

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V

bspc config border_width         5
bspc config window_gap           10

bspc config top_padding          37
bspc config bottom_padding       0

# bspc config normal_border_color  "#44475a"
# bspc config active_border_color  "#FFB162"
# bspc config focused_border_color "#FFFFFF"
# bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

inner1='FFFFFF'  # focused
inner2='44475a'  # normal

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "4" -o "9" $* |:; }

initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
    done
